// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKkWxSntTIuNpNbdi5By8g28MetvpEGm8',
    appId: '1:1071220220529:web:a5b8ae5f28924de2e271d0',
    messagingSenderId: '1071220220529',
    projectId: 'ngo-link-new',
    authDomain: 'ngo-link-new.firebaseapp.com',
    storageBucket: 'ngo-link-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5qZO5gnUwcScwgaG4gDPrLxD15y-6FQ',
    appId: '1:1071220220529:android:f141cc2ad251af5ae271d0',
    messagingSenderId: '1071220220529',
    projectId: 'ngo-link-new',
    storageBucket: 'ngo-link-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUIk9l8tKLTwTdcKNZZxMH7oE0H35sM0A',
    appId: '1:1071220220529:ios:651b598130c8136ee271d0',
    messagingSenderId: '1071220220529',
    projectId: 'ngo-link-new',
    storageBucket: 'ngo-link-new.appspot.com',
    iosClientId: '1071220220529-vp1o46okkbtv09a1manlj2972tubn2i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUIk9l8tKLTwTdcKNZZxMH7oE0H35sM0A',
    appId: '1:1071220220529:ios:651b598130c8136ee271d0',
    messagingSenderId: '1071220220529',
    projectId: 'ngo-link-new',
    storageBucket: 'ngo-link-new.appspot.com',
    iosClientId: '1071220220529-vp1o46okkbtv09a1manlj2972tubn2i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoLink',
  );
}
