// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAysEHeYWeaPdviFjQ2w6mMEfpBtWM_w7s',
    appId: '1:829165328879:web:2a4e162b1fd0228f873e1a',
    messagingSenderId: '829165328879',
    projectId: 'ngo-link-6b71f',
    authDomain: 'ngo-link-6b71f.firebaseapp.com',
    storageBucket: 'ngo-link-6b71f.appspot.com',
    measurementId: 'G-QD9CTEZETZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4F9oVGC3vjF1zVSbtZtMH9k-b2dYK_Y',
    appId: '1:829165328879:android:ab5db280af76d04a873e1a',
    messagingSenderId: '829165328879',
    projectId: 'ngo-link-6b71f',
    storageBucket: 'ngo-link-6b71f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuud_YuqSW5qCHYUMlhf1vWeAxyLI7ohU',
    appId: '1:829165328879:ios:4cbee05bf67df084873e1a',
    messagingSenderId: '829165328879',
    projectId: 'ngo-link-6b71f',
    storageBucket: 'ngo-link-6b71f.appspot.com',
    iosClientId: '829165328879-umthsl8oo83457antp45lnccurafbrgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuud_YuqSW5qCHYUMlhf1vWeAxyLI7ohU',
    appId: '1:829165328879:ios:4cbee05bf67df084873e1a',
    messagingSenderId: '829165328879',
    projectId: 'ngo-link-6b71f',
    storageBucket: 'ngo-link-6b71f.appspot.com',
    iosClientId: '829165328879-umthsl8oo83457antp45lnccurafbrgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoLink',
  );
}
